services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: ong_postgres
    environment:
      POSTGRES_DB: ong_management
      POSTGRES_USER: ong_user
      POSTGRES_PASSWORD: ong_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ong_network

  # Zookeeper para Kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: ong_zookeeper
    ports:
      - "2181:2181"
    networks:
      - ong_network

  # Apache Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: ong_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    networks:
      - ong_network

  # MailHog - Servidor SMTP de prueba con UI web
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ong_mailhog
    ports:
      - "1025:1025"  # Puerto SMTP
      - "8025:8025"  # Puerto Web UI
    networks:
      - ong_network

volumes:
  postgres_data:

networks:
  ong_network:
    driver: bridge