services:
  # Zookeeper para Kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: ong_zookeeper
    ports:
      - "2181:2181"
    networks:
      - ong_network

  # Apache Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: ong_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "solicitud-donaciones:1:1,transferencia-donaciones:1:1,oferta-donaciones:1:1,baja-solicitud-donaciones:1:1,eventossolidarios:1:1,baja-evento-solidario:1:1,adhesion-evento:1:1,transferencia-donaciones-empuje-comunitario:1:1,adhesion-evento-empuje-comunitario:1:1"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/kafka
    networks:
      - ong_network

  # MailHog - Servidor SMTP de prueba con UI web
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ong_mailhog
    ports:
      - "1025:1025"  # Puerto SMTP
      - "8025:8025"  # Puerto Web UI
    networks:
      - ong_network

volumes:
  kafka_data:

networks:
  ong_network:
    driver: bridge